# This is a basic workflow to help you get started with Actions

name: build-resume

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

jobs:
  build-resume:
    runs-on: ubuntu-latest
    container: pandoc/latex:2.9
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add make texlive git

      - name: Build Resume
        run: |
          export TEXMF=/usr/share/texmf-dist
          make html
          ls  /__w/resume/resume/output

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /__w/resume/resume/output
